// <auto-generated />
using DiscordApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscordApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220302205622_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscordApi.LeagueApi.Models.User", b =>
                {
                    b.Property<string>("Puuid")
                        .HasColumnType("text");

                    b.Property<decimal?>("AuthorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("SummName")
                        .HasColumnType("text");

                    b.HasKey("Puuid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
